#!/usr/bin/env node

var path = require('path')
var fs   = require('fs')
var root  = path.dirname(fs.realpathSync(__filename))

argv = process.argv.slice(2)
require(root + '/lib/cmd')(process.stdin, process.stdout, process.stderr)(argv)
